Home work2
LordMixa/HillelHomeWork1 pull request #1
Opened 2024-06-21 08:48 UTC by LordMixa

Check HomeWork2

2024-06-21 09:56 UTC, Delvin09 requested changes

2024-06-21 09:56 UTC, Delvin09 commented on HillelHomeWork2/Program.cs
> +            char[] arr = dnk.ToCharArray();
Такое себе сжатие, будет немного эффективно если входная строка будет состоять из последовательных одинаковых значений > 3.

2024-06-21 09:56 UTC, Delvin09 commented on HillelHomeWork2/Program.cs
> +            using (Aes aesAlg = Aes.Create())
Ок, но необходимо было реализовать свой алгоритм шифрования.

2024-06-21 18:18 UTC, LordMixa commented on HillelHomeWork2/Program.cs
> +            char[] arr = dnk.ToCharArray();
Добрий день, в завданні 5 стискання мається на увазі у візуальному вигляді типу А3С2? чи стискання в плані пам'яті?

2024-06-23 09:49 UTC, Delvin09 approved these changes

2024-06-24 18:22 UTC, merged